In [4]:
import pickle
import pandas as pd

In [2]:
with open('wide_df.pkl', 'rb') as f:
    wide_df = pickle.load(f)

In [3]:
wide_df.head()

,year,station,lev_type,day,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,2010,0463,MIN,1,0.24,0.19,0.21,0.22,0.23,0.23,0.26,0.25,0.24,0.21,0.39,0.24
1,2010,0463,MIN,2,0.24,0.20,0.20,0.23,0.25,0.24,0.25,0.26,0.25,0.21,0.37,0.24
2,2010,0463,MIN,3,0.23,0.21,0.22,0.22,0.25,0.24,0.26,0.26,0.26,0.21,0.30,0.23
3,2010,0463,MIN,4,0.22,0.21,0.21,0.22,0.27,0.22,0.26,0.26,0.27,0.21,0.27,0.22
4,2010,0463,MIN,5,0.22,0.22,0.21,0.21,0.27,0.24,0.25,0.27,0.26,0.23,0.30,0.22

In [ ]:
avg_levs = wide_df.